export const NOTIFIER_SUCCESS = 'NOTIFIER_SUCCESS'
export const NOTIFIER_FAIL = 'NOTIFIER_FAIL' 
export const NOTIFIER_DETAILS_SUCCESS = 'NOTIFIER_DETAILS_SUCCESS'
export const NOTIFIER_DETAILS_FAIL = 'NOTIFIER_DETAILS_FAIL' 
export const CLEAR_ERRORS = 'CLEAR_ERRORS' 



export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL' 
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET' 
export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST' 


export const NEW_NOTIFIER_SUCCESS = 'NEW_NOTIFIER_SUCCESS'
export const NEW_NOTIFIER_FAIL = 'NEW_NOTIFIER_FAIL' 
export const NEW_NOTIFIER_RESET = 'NEW_NOTIFIER_RESET' 
export const NEW_NOTIFIER_REQUEST = 'NEW_NOTIFIER_REQUEST' 



export const UPDATE_NOTIFIER_SUCCESS = 'UPDATE_NOTIFIER_SUCCESS'
export const UPDATE_NOTIFIER_FAIL = 'UPDATE_NOTIFIER_FAIL' 
export const UPDATE_NOTIFIER_RESET = 'UPDATE_NOTIFIER_RESET' 
export const UPDATE_NOTIFIER_REQUEST = 'UPDATE_NOTIFIER_REQUEST' 


export const DELETE_NOTIFIER_SUCCESS = 'DELETE_NOTIFIER_SUCCESS'
export const DELETE_NOTIFIER_FAIL = 'DELETE_NOTIFIER_FAIL' 
export const DELETE_NOTIFIER_RESET = 'DELETE_NOTIFIER_RESET' 
export const DELETE_NOTIFIER_REQUEST = 'DELETE_NOTIFIER_REQUEST' 


export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL' 
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET' 
export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST' 



export const CAN_REVIEW_SUCCESS = 'CAN_REVIEW_SUCCESS'
export const CAN_REVIEW_FAIL = 'CAN_REVIEW_FAIL' 
export const CAN_REVIEW_REQUEST = 'CAN_REVIEW_REQUEST' 


export const ADMIN_NOTIFIERS_SUCCESS = 'ADMIN_NOTIFIERS_SUCCESS'
export const ADMIN_NOTIFIERS_FAIL = 'ADMIN_NOTIFIERS_FAIL' 
export const ADMIN_NOTIFIERS_REQUEST = 'ADMIN_NOTIFIERS_REQUEST' 


export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL' 
export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST' 
